#import './Therapist.fragment.gql'

mutation createTherapist($clinic_id: ID!, $therapist: TherapistInput!) {
    createTherapist(clinic_id: $clinic_id, therapist: $therapist) {
        ...TherapistFields
    }
}