mutation editTreatmentSeries(
$id: Int!
$name: String
$treatments_number: Int!
) {
    editTreatmentSeries(
        id: $id
        name: $name
        treatments_number: $treatments_number
    ) {
        status
    }
}
