#import './TreatmentFragment.fragment.gql'

query treatments($patient_id: ID, $clinic_id: ID) {
    treatmentSeries(patient_id: $patient_id, clinic_id: $clinic_id) {
        ...TreatmentFragment
    }
    therapists(clinic_id: $clinic_id) {
        id
        id_number
        first_name
        last_name
    }
}
