#import './TreatmentFragment.fragment.gql'
#import './TreatmentSeriesObject.fragment.gql'

query treatments($patient_id: ID, $clinic_id: ID, $therapist_id: ID) {
    treatmentSeries(patient_id: $patient_id, clinic_id: $clinic_id, therapist_id: $therapist_id) {
        ...TreatmentFragment
    }
    treatmentsList(patient_id: $patient_id, clinic_id: $clinic_id, therapist_id: $therapist_id) {
        id
        target
        method
        process
        parents_guidance
        next_treatment_remark
        therapists {
            id
            id_number
            first_name
            last_name
        }
        patient {
            id
            first_name
            last_name
        }
        start_date
        end_date
    }
    treatmentObjects(patient_id: $patient_id, clinic_id: $clinic_id, therapist_id: $therapist_id) {
        ...TreatmentSeriesObjectFragment
    }
    past_treatments(patient_id: $patient_id)
    future_treatments(patient_id: $patient_id)
    total_treatments(patient_id: $patient_id)
    school_observations(patient_id: $patient_id)
    staff_meetings(patient_id: $patient_id)
    outside_source_consults(patient_id: $patient_id)
    therapists(clinic_id: $clinic_id) {
        id
        id_number
        first_name
        last_name
    }
}
