#import './TreatmentSeriesObject.fragment.gql'

mutation updateTreatmentSeriesObject($id: ID!, $object: TreatmentSeriesObjectInput!) {
    updateTreatmentSeriesObject(id: $id, object: $object) {
        ...TreatmentSeriesObjectFragment
    }
}
